---
driver:
  name: docker
  binary: /usr/bin/docker
  use_sudo: false
  
provisioner:
  name: chef_zero
  roles_path:  ../../roles
  nodes_path:  ../../nodes
  data_bags_path:  ../../data_bags
  environments_path:  ../../environments
  cookbook_path:  ../../cookbooks
  solo_rb_path:  ../../solo.rb

platforms:
  - name: centos
    driver_config:
      image: ibmdst/ibm_rhel_devops
      platform: rhel

suites:
  - name: default
    run_list:
      - role[helloworld_role]
      - recipe[test-helper]
      
  - name: default2
    run_list:
      - role[helloworld2_role]
      - recipe[test-helper]
